version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: codeflow-mysql
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/database:/docker-entrypoint-initdb.d
    networks:
      - codeflow-network

  # Backend API Server
  backend:
    build: ./src/server
    container_name: codeflow-backend
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      # ===== BACKEND CONFIGURATION =====
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      
      # Database Configuration
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      
      # Security & Auth
      SECRET_KEY: ${SECRET_KEY}
      ORIGIN: ${ORIGIN}
      FRONTEND_URL: ${FRONTEND_URL}
      CREDENTIALS: ${CREDENTIALS}
      
      # Logging
      LOG_FORMAT: ${LOG_FORMAT}
      LOG_DIR: ${LOG_DIR}
      
      # GitHub Integration (Backend)
      ORGANIZATION_NAME: ${ORGANIZATION_NAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_WEBHOOK_SECRET: ${GITHUB_WEBHOOK_SECRET}
      WEBHOOK_URL: ${WEBHOOK_URL}
      
      # AI & Analysis Services
      GEMINI_TOKEN: ${GEMINI_TOKEN}
      SONAR_TOKEN: ${SONAR_TOKEN}
      SONAR_ORG_TOKEN: ${SONAR_ORG_TOKEN}
      
      # Email Configuration
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_FROM: ${SMTP_FROM}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - backend_uploads:/app/uploads
      - backend_logs:/app/logs
    networks:
      - codeflow-network
    depends_on:
      - mysql
      - redis
    expose:
      - "3001"

  # Frontend Next.js App
  frontend:
    build: ./src/client
    container_name: codeflow-frontend
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      # ===== FRONTEND CONFIGURATION =====
      NODE_ENV: production
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      
      # Firebase Configuration
      NEXT_PUBLIC_FIREBASE_API_KEY: ${NEXT_PUBLIC_FIREBASE_API_KEY}
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
      NEXT_PUBLIC_FIREBASE_APP_ID: ${NEXT_PUBLIC_FIREBASE_APP_ID}
      NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}
      
      # API Configuration
      NEXT_PUBLIC_API_URL: ${NEXTAUTH_URL}/api
      NEXT_PUBLIC_IMAGE_URL: ${NEXTAUTH_URL}/api
      NEXT_PUBLIC_SECRET_KEY: ${NEXT_PUBLIC_SECRET_KEY}
      NEXT_PUBLIC_ORG_NAME: ${NEXT_PUBLIC_ORG_NAME}
    ports:
      - "3002:3002"
    networks:
      - codeflow-network
    depends_on:
      - backend
    expose:
      - "3002"
      
  # Redis
  redis:
    image: redis:7-alpine
    container_name: codeflow-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - codeflow-network

volumes:
  mysql_data:
    driver: local
  backend_uploads:
    driver: local
  backend_logs:
    driver: local
  redis_data:
    driver: local

networks:
  codeflow-network:
    driver: bridge