import { ITopic } from '../../../interfaces/topic';
export const mockData: ITopic[] = [
  {
    id: '1',
    title: 'Cơ bản về Học máy',
    description:
      'Khám phá những kiến thức cơ bản về thuật toán học máy và ứng dụng của chúng trong các tình huống thực tế.',
    authorId: 'user1',
    isCustom: false,
    courseId: 'course1',
    status: 'approved',
    members: [
      { id: 'string', userId: 'string', topicId: 'string', role: 'string' },
      { id: 'string', userId: 'string', topicId: 'string', role: 'string' },
    ],
    course: {
      id: 'course1',
      title: 'Khóa học Học máy',
      description: 'Học những kiến thức cơ bản về học máy và ứng dụng của nó.',
      authorId: 'user1',
      startDate: new Date(new Date().getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      endDate: new Date().toISOString(),
      regStartDate: new Date().toISOString(),
      regEndDate: new Date().toISOString(),
      topicDeadline: new Date(new Date().getTime() + 30 * 24 * 60 * 60 * 1000).toISOString(),
      status: true,
      maxGroupMembers: 10,
      topicCount: 10,
      enrollmentCount: 10,
      type: 'course',
    },
    tags: [
      { id: 'tag1', name: 'machine-learning' },
      { id: 'tag2', name: 'ai' },
      { id: 'tag3', name: 'algorithms' },
    ],
  },
  {
    id: '2',
    title: 'Phát triển Web với React',
    description:
      'Xây dựng các ứng dụng web hiện đại sử dụng React, hooks và thư viện quản lý trạng thái.',
    authorId: 'user2',
    isCustom: true,
    courseId: 'course1',
    status: 'pending',
    members: [
      { id: 'string', userId: 'string', topicId: 'string', role: 'string' },
      { id: 'string', userId: 'string', topicId: 'string', role: 'string' },
    ],
    course: {
      id: 'course1',
      title: 'Khóa học Phát triển Web',
      description: 'Học những kiến thức cơ bản về phát triển web và ứng dụng của nó.',
      authorId: 'user1',
      startDate: new Date(new Date().getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      endDate: new Date().toISOString(),
      regStartDate: new Date().toISOString(),
      regEndDate: new Date().toISOString(),
      topicDeadline: new Date(new Date().getTime() + 10 * 24 * 60 * 60 * 1000).toISOString(),
      status: true,
      maxGroupMembers: 10,
      topicCount: 10,
      enrollmentCount: 10,
      type: 'course',
    },
    tags: [
      { id: 'tag4', name: 'react' },
      { id: 'tag5', name: 'javascript' },
      { id: 'tag6', name: 'frontend' },
    ],
  },
  {
    id: '3',
    title: 'Thiết kế và Tối ưu hóa Cơ sở dữ liệu',
    description:
      'Học cách thiết kế các lược đồ cơ sở dữ liệu hiệu quả và tối ưu hóa hiệu suất truy vấn.',
    authorId: 'user3',
    isCustom: false,
    courseId: 'course2',
    status: 'approved',
    course: {
      id: 'course1',
      title: 'Khóa học Thiết kế và Tối ưu hóa Cơ sở dữ liệu',
      description: 'Học những kiến thức cơ bản về thiết kế cơ sở dữ liệu và ứng dụng của nó.',
      authorId: 'user1',
      startDate: new Date().toISOString(),
      endDate: new Date().toISOString(),
      regStartDate: new Date().toISOString(),
      regEndDate: new Date().toISOString(),
      topicDeadline: new Date().toISOString(),
      status: true,
      maxGroupMembers: 10,
      topicCount: 10,
      enrollmentCount: 10,
      type: 'course',
    },
    tags: [
      { id: 'tag7', name: 'database' },
      { id: 'tag8', name: 'sql' },
      { id: 'tag9', name: 'optimization' },
    ],
  },
  {
    id: '4',
    title: 'Phát triển Ứng dụng Di động',
    description: 'Tạo các ứng dụng di động đa nền tảng sử dụng React Native và Flutter.',
    authorId: 'user4',
    isCustom: true,
    courseId: 'course2',
    status: 'rejected',
    course: {
      id: 'course1',
      title: 'Khóa học Phát triển Ứng dụng Di động',
      description: 'Học những kiến thức cơ bản về phát triển ứng dụng di động và ứng dụng của nó.',
      authorId: 'user1',
      startDate: new Date(new Date().getTime() - 80 * 24 * 60 * 60 * 1000).toISOString(),
      endDate: new Date().toISOString(),
      regStartDate: new Date().toISOString(),
      regEndDate: new Date().toISOString(),
      topicDeadline: new Date(new Date().getTime() + 10 * 24 * 60 * 60 * 1000).toISOString(),
      status: true,
      maxGroupMembers: 10,
      topicCount: 10,
      enrollmentCount: 10,
      type: 'course',
    },
    tags: [
      { id: 'tag10', name: 'mobile' },
      { id: 'tag11', name: 'react-native' },
      { id: 'tag12', name: 'flutter' },
    ],
  },
  {
    id: '5',
    title: 'Kiến trúc Điện toán Đám mây',
    description:
      'Thiết kế và triển khai các giải pháp đám mây có thể mở rộng sử dụng AWS, Azure và Google Cloud.',
    authorId: 'user5',
    isCustom: false,
    courseId: 'course3',
    status: 'approved',
    course: {
      id: 'course1',
      title: 'Khóa học Kiến trúc Điện toán Đám mây',
      description: 'Học những kiến thức cơ bản về điện toán đám mây và ứng dụng của nó.',
      authorId: 'user1',
      startDate: new Date().toISOString(),
      endDate: new Date().toISOString(),
      regStartDate: new Date().toISOString(),
      regEndDate: new Date().toISOString(),
      topicDeadline: new Date().toISOString(),
      status: true,
      maxGroupMembers: 10,
      topicCount: 10,
      enrollmentCount: 10,
      type: 'course',
    },
    tags: [
      { id: 'tag13', name: 'cloud' },
      { id: 'tag14', name: 'aws' },
      { id: 'tag15', name: 'architecture' },
    ],
  },
  {
    id: '6',
    title: 'Thực hành Tốt nhất về An ninh mạng',
    description: 'Hiểu về các lỗ hổng bảo mật và triển khai các biện pháp bảo mật mạnh mẽ.',
    authorId: 'user6',
    isCustom: true,
    courseId: 'course3',
    status: 'pending',
    course: {
      id: 'course1',
      title: 'Khóa học Thực hành Tốt nhất về An ninh mạng',
      description: 'Học những kiến thức cơ bản về an ninh mạng và ứng dụng của nó.',
      authorId: 'user1',
      startDate: new Date().toISOString(),
      endDate: new Date().toISOString(),
      regStartDate: new Date().toISOString(),
      regEndDate: new Date().toISOString(),
      topicDeadline: new Date().toISOString(),
      status: true,
      maxGroupMembers: 10,
      topicCount: 10,
      enrollmentCount: 10,
      type: 'course',
    },
    tags: [
      { id: 'tag16', name: 'security' },
      { id: 'tag17', name: 'cybersecurity' },
      { id: 'tag18', name: 'encryption' },
    ],
  },
  {
    id: '7',
    title: 'Khoa học Dữ liệu và Phân tích',
    description:
      'Phân tích các tập dữ liệu lớn và trích xuất những hiểu biết có ý nghĩa sử dụng Python và R.',
    authorId: 'user7',
    isCustom: false,
    courseId: 'course4',
    status: 'approved',
    course: {
      id: 'course1',
      title: 'Khóa học Khoa học Dữ liệu và Phân tích',
      description: 'Học những kiến thức cơ bản về khoa học dữ liệu và ứng dụng của nó.',
      authorId: 'user1',
      startDate: new Date().toISOString(),
      endDate: new Date().toISOString(),
      regStartDate: new Date().toISOString(),
      regEndDate: new Date().toISOString(),
      topicDeadline: new Date().toISOString(),
      status: true,
      maxGroupMembers: 10,
      topicCount: 10,
      enrollmentCount: 10,
      type: 'course',
    },
    tags: [
      { id: 'tag19', name: 'data-science' },
      { id: 'tag20', name: 'python' },
      { id: 'tag21', name: 'analytics' },
    ],
  },
  {
    id: '8',
    title: 'DevOps và Pipeline CI/CD',
    description: 'Triển khai quy trình tích hợp liên tục và triển khai cho các ứng dụng hiện đại.',
    authorId: 'user8',
    isCustom: true,
    courseId: 'course4',
    status: 'pending',
    course: {
      id: 'course1',
      title: 'Khóa học DevOps và Pipeline CI/CD',
      description: 'Học những kiến thức cơ bản về DevOps và ứng dụng của nó.',
      authorId: 'user1',
      startDate: new Date().toISOString(),
      endDate: new Date().toISOString(),
      regStartDate: new Date().toISOString(),
      regEndDate: new Date().toISOString(),
      topicDeadline: new Date().toISOString(),
      status: true,
      maxGroupMembers: 10,
      topicCount: 10,
      enrollmentCount: 10,
      type: 'course',
    },
    tags: [
      { id: 'tag22', name: 'devops' },
      { id: 'tag23', name: 'ci-cd' },
      { id: 'tag24', name: 'automation' },
    ],
  },
];
